name: cote
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1  # Move this to the same level as other dependencies

  # Core
  cupertino_icons: ^1.0.2

  # Firebase Services
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6

  # Authentication
  google_sign_in: ^6.1.5

  # State Management
  provider: ^6.0.5
  shared_preferences: ^2.2.1

  # PDF & Document Handling
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.1
  pdfx: ^2.4.0
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  cached_network_image: ^3.2.3

  # Network
  http: ^1.1.0

  # UI Components
  shimmer: ^3.0.0

  # Video & Media
  video_player: ^2.7.1
  image_picker: ^1.0.4
  file_selector: ^1.0.1

  # AI & Text Processing
  google_generative_ai: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/